# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8953845ba554967984c07e5e49fddb7d6dd6d28d2939abe951fe0478b703b35aff842a1ab276c652f15911c2f37db41e53c4e464bf793360f21af8906fbb157f

test:
  secret_key_base: a3ff748b6ad572057043611b7364b1c51808861bd34f0a5b8c07d75110105b859e9c5e8bb009bfc5a9fbf743d04530b9aa2d9f4f96d606f8f31cb84c8789be5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
