# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46a346057332ca86cd499d6d061a370c3b48b1a07a99435805af2b438cd23eb1279ee9d21050569b9b89ab3366004f3c27836e9653d026bf61ecc066f6b6c925

test:
  secret_key_base: 0822c17c1c48e827c28fd0c57e26e866f52d388012569e033204d9b3ddb4e841138a1ff84a389a24674ba8bbff911591ce07ce8d1381f19a247939dcce4d4a1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
